// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuaExpr8YF1UAVreuQIIUxODTlx3QVvlU',
    appId: '1:841271160808:web:0fc6d26869a1c9d1d1be5d',
    messagingSenderId: '841271160808',
    projectId: 'fundmatch-d3750',
    authDomain: 'fundmatch-d3750.firebaseapp.com',
    databaseURL: 'https://fundmatch-d3750-default-rtdb.firebaseio.com',
    storageBucket: 'fundmatch-d3750.firebasestorage.app',
    measurementId: 'G-LP293Q6PXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLelcRwy8ICNRdPmzc3qD8frZ92gUhqeY',
    appId: '1:841271160808:android:e85b49cf64db33e0d1be5d',
    messagingSenderId: '841271160808',
    projectId: 'fundmatch-d3750',
    databaseURL: 'https://fundmatch-d3750-default-rtdb.firebaseio.com',
    storageBucket: 'fundmatch-d3750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfU-yaJGawNFaFWdyqkuX9v2Yo4ESp-o',
    appId: '1:841271160808:ios:f16f97ae010aeed8d1be5d',
    messagingSenderId: '841271160808',
    projectId: 'fundmatch-d3750',
    databaseURL: 'https://fundmatch-d3750-default-rtdb.firebaseio.com',
    storageBucket: 'fundmatch-d3750.firebasestorage.app',
    iosClientId: '841271160808-ioh53bh0fovegco94bq2p86t65e6gsen.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfU-yaJGawNFaFWdyqkuX9v2Yo4ESp-o',
    appId: '1:841271160808:ios:f16f97ae010aeed8d1be5d',
    messagingSenderId: '841271160808',
    projectId: 'fundmatch-d3750',
    databaseURL: 'https://fundmatch-d3750-default-rtdb.firebaseio.com',
    storageBucket: 'fundmatch-d3750.firebasestorage.app',
    iosClientId: '841271160808-ioh53bh0fovegco94bq2p86t65e6gsen.apps.googleusercontent.com',
    iosBundleId: 'com.example.officeControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuaExpr8YF1UAVreuQIIUxODTlx3QVvlU',
    appId: '1:841271160808:web:245c134995673120d1be5d',
    messagingSenderId: '841271160808',
    projectId: 'fundmatch-d3750',
    authDomain: 'fundmatch-d3750.firebaseapp.com',
    databaseURL: 'https://fundmatch-d3750-default-rtdb.firebaseio.com',
    storageBucket: 'fundmatch-d3750.firebasestorage.app',
    measurementId: 'G-4TER34VFG6',
  );
}
